=== pardeev/ReactApplication/JSONSchema/netSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Network Visualization Format",
    "descriptions": "Network Visualization format compatible with NetworkX JSON graph",
    "definitions": {
        "node": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "minLength": 1
                },
                "type": {"type": "string"},
                "x": {"type": "number"},
                "y": {"type": "number"},
                "layer": {"type": "string"},
                "ipv4": {"type": "string"},
                "mac": {"type": "string"}
            },
            "required": ["id", "x", "y"]
        },
        "link": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "capacity": {
                    "type": "number",
                    "minimum": 0
                },
                "weight": {
                    "type": "number",
                    "minimum": 0
                },
                "ports": {
                    "type": "object"
                }
            },
            "required": ["source", "target"]
        }
    },

    "type": "object",
    "properties": {
        "nodes": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/node"
            }
        },
        "links": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/link"
            }
        },
        "graph": {"type": "object",
            "properties": {
                "name": {"type": "string"},
                "desc": {"type": "string"}
            }},
        "directed": {"type": "boolean"},
        "multigraph": {"type": "boolean"}
    },
    "required": ["nodes"]
}

=== pardeev/ReactApplication/JSONSchema/KShortTest1Net.json
{
    "directed": false,
    "multigraph": false,
    "graph": {
        "name": "KShortTest1Net",
        "desc": "An extremely simple network to test K-shortest path algorithms"
    },
    "nodes": [
        {
            "id": "N0",
            "x": 296.77,
            "y": 29.66,
            "type": "switch"
        },
        {
            "id": "N1",
            "x": 338.77,
            "y": 135.66,
            "type": "switch"
        },
        {
            "id": "N2",
            "x": 258.77,
            "y": 169.66,
            "type": "switch"
        },
        {
            "id": "N3",
            "x": 203.77,
            "y": 67.66,
            "type": "switch"
        },
        {
            "id": "N4",
            "x": 425.77,
            "y": 61.66,
            "type": "switch"
        }
    ],
    "links": [
        {
            "source": "N4",
            "target": "N1",
            "capacity": 50,
            "weight": 10
        },
        {
            "source": "N4",
            "target": "N0",
            "capacity": 40,
            "weight": 7
        },
        {
            "source": "N0",
            "target": "N1",
            "capacity": 45,
            "weight": 10
        },
        {
            "source": "N3",
            "target": "N0",
            "capacity": 50,
            "weight": 10
        },
        {
            "source": "N1",
            "target": "N2",
            "capacity": 42,
            "weight": 15
        },
        {
            "source": "N2",
            "target": "N3",
            "capacity": 30,
            "weight": 12
        }
    ]
}
